### ISSUE TITLE
Java Heap Space Error caused by an 'Out Of Memory' Error

### ISSUE THREAD

**Issue by CleanHit** [heremaps/oss-review-toolkit#2272]
At the end of the **analyzer-result.yml** file I see:
```yaml
      'Gradle::app/build.gradle:':
      - timestamp: "2020-02-25T16:08:48.310903Z"
        source: "Gradle"
        message: "Resolving dependencies for 'build.gradle' failed with: BuildException:\
          \ Could not fetch model of type 'DependencyTreeModel' using Gradle distribution\
          \ 'https://services.gradle.org/distributions/gradle-5.4.1-all.zip'.\nCaused\
          \ by: LocationAwareException: Java heap space\nCaused by: OutOfMemoryError:\
          \ Java heap space"
        severity: "ERROR"
    has_issues: true
```
I've this setting in my global **.gradle/gradle.properties** file:
```gradle
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx6g -XX:MaxPermSize=4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
```
I think I give enough memory to Gradle or do I need to set the setting above in some other **gradle.properties** file? If I understood it correctly then, it fails to resolve the dependencies for 'build.gradle' because of that `OutOfMemoryError`. 

I'm using:
- Fedora 31 OS
- OpenJDK 12
- gradle -v output:
```bash
------------------------------------------------------------
Gradle 6.2
------------------------------------------------------------

Build time:   2020-02-17 08:32:01 UTC
Revision:     61d3320259a1a0d31519bf208eb13741679a742f

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          12.0.2 ("Oracle Corporation" 12.0.2+13)
OS:           Linux 5.5.5-200.fc31.x86_64 amd64

```
