### ISSUE TITLE
A Possible Problem using Regex in Exclude Pattern

### ISSUE THREAD

**Issue by CleanHit** [heremaps/oss-review-toolkit#2292]
I have an `.ort.yml` file with this content to manage my scope excludes:
```yaml
excludes:
  scopes:
  - pattern: "^(?!.*\bcurrentProdReleaseRuntimeClasspath\b).*$"
    reason: "BUILD_DEPENDENCY_OF"
    comment: "Packages for testing or development only."
``` 
The **Static Html** `scan-report.html` file shows this entry repeatedly in the **Scopes** column:
```
currentProdReleaseRuntimeClasspath Excluded: 
BUILD_DEPENDENCY_OF - Packages for testing or development only.
```
Does this mean that my regix is not being interpreted properly? Because everything but `currentProdReleaseRuntimeClasspath` has to be excluded.

**Comment by CleanHit** [comment]
I've also noticed that all of the listed libraries in the **cycloneDX** `bom.xml` file have:
```xml
<scope>excluded</scope>
```
I guess that using my pattern all the libraries in the `currentProdReleaseRuntimeClasspath` scope suppose to have this entry:
```xml
<scope>included</scope>
```
I'm I correct?

**Comment by sschuberth** [comment]
I believe your regex is wrong, please try `^(?!currentProdReleaseRuntimeClasspath$).*$` instead.

**Comment by CleanHit** [comment]
Thanks, I'll try yours tomorrow. My [regex](https://regex101.com/r/d8uGIr/1) is not wrong, but yours is better because it also filters one line inputs like `currentProdReleaseRuntimeClasspath, fooBarFoo`.

**Comment by CleanHit** [comment]
@sschuberth The scan takes now longer with your suggested `patter:` than with my `pattern:` (though it's not wrong). My question is what happens if the regex expression is wrong or not working? What is the default behaviour  for `--skip-excluded` if it cant interpret the regex expression correctly?

**Comment by sschuberth** [comment]
See [this code](https://github.com/heremaps/oss-review-toolkit/blob/beb527b4e5156f0117b11688a6728fa1cde0496b/model/src/main/kotlin/config/ScopeExclude.kt#L49): Either `matches` is `true` and the scope is excluded, or `matches` is `false` and the scope is not excluded. If the pattern is not a regular expression at all, then an uncaught exception would be thrown.

BTW, there are different flavors of regular expressions. Your [link](https://regex101.com/r/d8uGIr/1) uses "PCRE (PHP)" (see the left-hand menu) which is slightly different from the regex flavor Java / Kotlin use. You can verify e.g. at https://www.regexplanet.com/advanced/java/index.html that my regex `^(?!currentProdReleaseRuntimeClasspath$).*$` works.

**Comment by CleanHit** [comment]
I've tried [my regex](https://www.regexplanet.com/share/index.html?share=yyyyd207ekr) with your link and after choosing **Java** it showed `"^(?!.*\\bcurrentProdReleaseRuntimeClasspath\\b).*$"` as a **Java string**. Does it mean that I have to escape my backslashes in the `pattern:` if I want to use my regex?

**Comment by sschuberth** [comment]
> Does it mean that I have to escape my backslashes in `pattern:` if I want to use my regex?

Yes, indeed. The pattern is read as a string from which a regex is constructed, so you need to escape backslashes that must stay literal backslashes as part of a regex.

**Comment by CleanHit** [comment]
I can see that your `pattern:` works. I won't be testing it again with mine, but I guess it will also work after escaping the the backslashes.

**Comment by CleanHit** [comment]
@sschuberth If the exclude pattern `^(?!currentProdReleaseRuntimeClasspath$).*$` works as it should then my _analyzer-result.yml_ file should have dependencies listed only for `currentProdReleaseRuntimeClasspath` and all the other ones should be empty, e.g.:
```yml
- name: "currentProdReleaseRuntime"
  dependencies: []
- name: "currentProdReleaseRuntimeClasspath"
  dependencies:
  - id: "Maven:androidx.appcompat:appcompat:1.1.0"
    dependencies:
    - id: "Maven:androidx.annotation:annotation:1.1.0"
    - id: "Maven:androidx.appcompat:appcompat-resources:1.1.0"
    ...
    ...
- name: "androidTestImplementationDependenciesMetadata"
  dependencies: []
- name: "_internal_aapt2_binary"
  dependencies: []
```
Am I correct?
