### ISSUE TITLE
Curations: allows setting multiple VCS paths via glob expressions

### ISSUE THREAD

**Issue by tsteenbe** [heremaps/oss-review-toolkit#2313]
Propose to change path in [VcsInfoCuration](https://github.com/heremaps/oss-review-toolkit/blob/master/reporter-web-app/src/models/VcsInfoCuration.js) from a string to a glob expression to allow specifying a curation where the path is only a subset of directories within a directory.

**Use Case**

Try to create a path curation for `Maven:org.spekframework.spek2:spek-runner-common` and based on comparing [spek-runtime-jvm-2.1.0-alpha.0.9+f51c732-sources.jar](https://dl.bintray.com/spekframework/spek-dev/org/spekframework/spek2/spek-runtime-jvm/2.1.0-alpha.0.9+f51c732/:spek-runtime-jvm-2.1.0-alpha.0.9+f51c732-sources.jar) and https://github.com/spekframework/spek the code for this package is in 

- `spek/spek-runtime/src/{commonMain/kotlin/org/spekframework/spek`
- `spek-runtime/src/jvmMain/kotlin/org/spekframework/spek2`

Can do a path curation on [spek-runtime/src](https://github.com/spekframework/spek/tree/2.x/spek-runtime/src) as this directory contains other directories that are not part of this package such as `spek-runtime/src/windowsMain` or `spek-runtime/src/linuxMain`

So the curation I would like to do is:

```
- id: "Maven:org.spekframework.spek2:spek-runtime-jvm"
  curations:
    comment: "...."
    vcs:
      url: "https://github.com/spekframework/spek"
      path: "spek/spek-runtime/src/{commonMain/kotlin/org/spekframework/spek2,spek-runtime/src/jvmMain/kotlin/org/spekframework/spek2/
}"

```
