### ISSUE TITLE
Downloader fails to understand the result of analyzer

### ISSUE THREAD

**Issue by CsatariGergely** [heremaps/oss-review-toolkit#998]
Hi, 
I generated an ort analyzis file with the analyzer and I provided this to the downloader as input. As a result I got an exception from downloader: 
```Instantiation of [simple type, class com.here.ort.model.AnalyzerResult] value failed for JSON property projects due to missing (therefore NULL) value for creator parameter projects which is a non-nullable type```

The provided ort analyzis file contains a projects property: 

```
---
repository:
  vcs:
    type: "Git"
    url: "https://github.com/facebook/react"
    revision: "409e472fcaae2b6c171f4e9a0c4b5ad88ec2bf21"
    path: ""
  vcs_processed:
    type: "git"
    url: "https://github.com/facebook/react.git"
    revision: "409e472fcaae2b6c171f4e9a0c4b5ad88ec2bf21"
    path: ""
  config: {}
analyzer:
  environment:
    os: "Linux"
    tool_versions: {}
  config:
    ignore_tool_versions: true
    allow_dynamic_versions: false
  result:
    projects:
```
Can you please help me to figure out what can be the problem?
Thanks
